import type { SupabaseClient } from "@supabase/supabase-js";

const demoClients = [
  {
    id: "10000000-0000-4000-8000-000000000101",
    slug: "restaurante-brasa-norte",
    name: "Restaurante Brasa Norte",
    legal_name: "Restaurante Brasa Norte Demo SL",
    sector: "Restaurante",
    city: "Castalla",
    status: "Activo",
    source: "demo",
    is_demo: true,
    demo_label: "Demo Firekworks",
    logo_url: "/brand/firekworks-icon.png",
    brand_colors: ["#1d1d1f", "#b7791f", "#f97316"],
    brand_voice: "Cercano, apetitoso, local y directo.",
    target_audience: "Parejas, familias y grupos locales.",
    objective: "Aumentar reservas de fin de semana.",
    services: ["Contenido mensual", "Meta Ads", "Google Business Profile", "WhatsApp"],
    average_ticket: 35,
    monthly_budget: 350,
    service_fee: 690,
    client_portal_enabled: true,
    portal_status: "demo",
    show_in_leaderboard: true,
    public_leaderboard_name: "Restaurante local demo",
    billing_name: "Restaurante Brasa Norte Demo SL",
    billing_email: "demo-brasa@firekworks.local",
    billing_address: "Calle Demo 12, Castalla"
  },
  {
    id: "10000000-0000-4000-8000-000000000102",
    slug: "clinica-dental-sonrisa-ibi",
    name: "Clínica Dental Sonrisa Ibi",
    legal_name: "Clinica Dental Sonrisa Ibi Demo SL",
    sector: "Clínica dental",
    city: "Ibi",
    status: "Activo",
    source: "demo",
    is_demo: true,
    demo_label: "Demo Firekworks",
    logo_url: "/brand/firekworks-icon.png",
    brand_colors: ["#0f9f8f", "#0071e3", "#f5f5f7"],
    brand_voice: "Profesional, tranquilo, educativo y basado en confianza.",
    target_audience: "Familias y adultos de Ibi que necesitan primera visita.",
    objective: "Captar primeras visitas y limpiezas.",
    services: ["Embudo de leads", "Landing", "Meta Ads", "Seguimiento"],
    average_ticket: 85,
    monthly_budget: 420,
    service_fee: 790,
    client_portal_enabled: true,
    portal_status: "demo",
    show_in_leaderboard: false,
    public_leaderboard_name: "Clínica dental demo",
    billing_name: "Clinica Dental Sonrisa Ibi Demo SL",
    billing_email: "demo-sonrisa@firekworks.local",
    billing_address: "Avenida Demo 8, Ibi"
  },
  {
    id: "10000000-0000-4000-8000-000000000103",
    slug: "fitbox-elda",
    name: "FitBox Elda",
    legal_name: "FitBox Elda Demo CB",
    sector: "Gimnasio",
    city: "Elda",
    status: "Activo",
    source: "demo",
    is_demo: true,
    demo_label: "Demo Firekworks",
    logo_url: "/brand/firekworks-icon.png",
    brand_colors: ["#001020", "#2f9e44", "#0071e3"],
    brand_voice: "Energético, motivador, competitivo y muy visual.",
    target_audience: "Personas de Elda que quieren probar entrenamiento funcional.",
    objective: "Captar nuevos socios con reels y prueba gratuita.",
    services: ["Reels", "Campañas Meta", "Prueba gratuita", "Reporting"],
    average_ticket: 49,
    monthly_budget: 290,
    service_fee: 690,
    client_portal_enabled: true,
    portal_status: "demo",
    show_in_leaderboard: true,
    public_leaderboard_name: "Gimnasio demo",
    billing_name: "FitBox Elda Demo CB",
    billing_email: "demo-fitbox@firekworks.local",
    billing_address: "Polígono Demo 4, Elda"
  }
];

const demoCampaigns = [
  {
    id: "20000000-0000-4000-8000-000000000101",
    client_id: demoClients[0].id,
    name: "Reservas fin de semana Brasa Norte",
    platform: "Meta Ads",
    objective: "Reservas",
    status: "active",
    start_date: "2026-06-01",
    end_date: "2026-06-30",
    budget: 350,
    spend: 350,
    planned_budget: 350,
    real_spend: 350,
    client_visible_summary: "Campaña demo para convertir alcance local en reservas por WhatsApp.",
    is_demo: true,
    campaign_type: "Reservas",
    offer: "Menú brasa de viernes a domingo con reserva por WhatsApp",
    target_audience: "Familias y grupos de Castalla",
    funnel_stage: "Conversión",
    recommendations: "Mantener creatividad con producto real y reforzar horarios de jueves.",
    launch_checklist: ["Oferta clara", "WhatsApp conectado", "Creatividades aprobadas"],
    metric_mode: "demo",
    source: "demo",
    sync_status: "manual",
    lifecycle_status: "active"
  },
  {
    id: "20000000-0000-4000-8000-000000000102",
    client_id: demoClients[1].id,
    name: "Primeras visitas Sonrisa Ibi",
    platform: "Meta Ads",
    objective: "Leads",
    status: "active",
    start_date: "2026-06-01",
    end_date: "2026-06-30",
    budget: 420,
    spend: 420,
    planned_budget: 420,
    real_spend: 420,
    client_visible_summary: "Embudo demo para captar primeras visitas y limpiezas mediante landing.",
    is_demo: true,
    campaign_type: "Captación WhatsApp",
    offer: "Primera visita + limpieza con diagnóstico inicial",
    target_audience: "Familias y adultos de Ibi",
    funnel_stage: "Conversión",
    recommendations: "Probar creatividades de confianza con doctora y proceso paso a paso.",
    launch_checklist: ["Landing revisada", "Formulario activo", "Creatividades de confianza"],
    metric_mode: "demo",
    source: "demo",
    sync_status: "manual",
    lifecycle_status: "active"
  },
  {
    id: "20000000-0000-4000-8000-000000000103",
    client_id: demoClients[2].id,
    name: "Prueba gratuita FitBox Elda",
    platform: "Instagram",
    objective: "Leads",
    status: "active",
    start_date: "2026-06-01",
    end_date: "2026-06-30",
    budget: 290,
    spend: 290,
    planned_budget: 290,
    real_spend: 290,
    client_visible_summary: "Campaña demo para transformar reels en formularios y pruebas reservadas.",
    is_demo: true,
    campaign_type: "Promoción local",
    offer: "Clase gratuita de entrenamiento funcional",
    target_audience: "Jóvenes y adultos activos de Elda",
    funnel_stage: "Conversión",
    recommendations: "Escalar reels con mayor retención y reforzar prueba social.",
    launch_checklist: ["Oferta prueba gratuita", "Formulario conectado", "Reels aprobados"],
    metric_mode: "demo",
    source: "demo",
    sync_status: "manual",
    lifecycle_status: "active"
  }
];

const demoMetrics = [
  {
    id: "30000000-0000-4000-8000-000000000101",
    client_id: demoClients[0].id,
    month: 6,
    year: 2026,
    reach: 42800,
    impressions: 91300,
    clicks: 602,
    leads: 121,
    messages: 318,
    bookings: 46,
    calls: 22,
    whatsapp_clicks: 318,
    website_clicks: 164,
    ad_spend: 350,
    service_fee: 690,
    extra_costs: 0,
    estimated_revenue: 1610,
    estimated_roi: 1.55,
    roi_type: "estimated",
    summary_client: "Demo de contenido local y anuncios convertidos en reservas medibles.",
    diagnosis_client: "El mayor potencial está en reforzar WhatsApp y creatividades de plato/ambiente.",
    next_month_plan_client: "Añadir reseñas y publicar 3 reels de producto.",
    data_status: "demo"
  },
  {
    id: "30000000-0000-4000-8000-000000000102",
    client_id: demoClients[1].id,
    month: 6,
    year: 2026,
    reach: 31200,
    impressions: 68400,
    clicks: 448,
    leads: 82,
    messages: 96,
    bookings: 29,
    calls: 18,
    whatsapp_clicks: 74,
    website_clicks: 146,
    ad_spend: 420,
    service_fee: 790,
    extra_costs: 0,
    estimated_revenue: 2465,
    estimated_roi: 2.04,
    roi_type: "estimated",
    summary_client: "Embudo demo de primeras visitas con landing, anuncios y seguimiento.",
    diagnosis_client: "La confianza clínica y una oferta clara reducen fricción.",
    next_month_plan_client: "Activar remarketing con prueba social.",
    data_status: "demo"
  },
  {
    id: "30000000-0000-4000-8000-000000000103",
    client_id: demoClients[2].id,
    month: 6,
    year: 2026,
    reach: 58400,
    impressions: 118900,
    clicks: 824,
    leads: 124,
    messages: 141,
    bookings: 37,
    calls: 11,
    whatsapp_clicks: 136,
    website_clicks: 209,
    ad_spend: 290,
    service_fee: 690,
    extra_costs: 0,
    estimated_revenue: 1813,
    estimated_roi: 1.85,
    roi_type: "estimated",
    summary_client: "Campaña intensa de reels y prueba gratuita para captar socios.",
    diagnosis_client: "El contenido real del box genera atención y formularios rápidos.",
    next_month_plan_client: "Duplicar reels ganadores y añadir testimonios.",
    data_status: "demo"
  }
];

const demoContent = [
  {
    id: "40000000-0000-4000-8000-000000000101",
    client_id: demoClients[0].id,
    campaign_id: demoCampaigns[0].id,
    content_code: "REEL-001",
    type: "Reel",
    platform: "Instagram",
    title: "Brasa encendida: reservas de viernes",
    caption: "Este viernes la brasa ya tiene nombre. Reserva por WhatsApp y ven con tu grupo.",
    status: "published",
    published_at: "2026-06-07T18:30:00+02:00",
    publish_date: "2026-06-07",
    due_date: "2026-06-05",
    url: "#",
    client_visible: true,
    objective: "Reservas de fin de semana",
    funnel_stage: "Conversión",
    hook: "El sonido de la brasa antes de abrir puertas.",
    visual_brief: "Plano corto de brasa, plato final, sala preparada y CTA.",
    cta: "Reservar por WhatsApp",
    preview_data: { format: "reel" },
    notes: "Demo interna. Diseño final en Canva/Adobe.",
    is_demo: true,
    source: "demo",
    sync_status: "manual",
    lifecycle_status: "published"
  },
  {
    id: "40000000-0000-4000-8000-000000000102",
    client_id: demoClients[1].id,
    campaign_id: demoCampaigns[1].id,
    content_code: "POST-001",
    type: "Post",
    platform: "Instagram",
    title: "Primera visita sin miedo",
    caption: "Tu primera visita empieza con calma: revisamos, explicamos y decidimos contigo.",
    status: "scheduled",
    published_at: null,
    publish_date: "2026-06-12",
    due_date: "2026-06-10",
    url: "#",
    client_visible: true,
    objective: "Captar primeras visitas",
    funnel_stage: "Confianza",
    hook: "Si hace tiempo que no vienes al dentista, esto es para ti.",
    visual_brief: "Post cuadrado con doctora, gabinete y puntos del proceso.",
    cta: "Pedir cita",
    preview_data: { format: "post" },
    notes: "Demo interna. Diseño final en Canva/Adobe.",
    is_demo: true,
    source: "demo",
    sync_status: "manual",
    lifecycle_status: "scheduled"
  },
  {
    id: "40000000-0000-4000-8000-000000000103",
    client_id: demoClients[2].id,
    campaign_id: demoCampaigns[2].id,
    content_code: "CAR-001",
    type: "Carrusel",
    platform: "Instagram",
    title: "5 razones para probar FitBox",
    caption: "No necesitas estar en forma para empezar. Necesitas empezar para estarlo.",
    status: "editing",
    published_at: null,
    publish_date: "2026-06-14",
    due_date: "2026-06-11",
    url: "#",
    client_visible: true,
    objective: "Reservar prueba gratuita",
    funnel_stage: "Consideración",
    hook: "¿Y si esta semana fuera la primera?",
    visual_brief: "Carrusel con portada fuerte, beneficios y última slide con CTA.",
    cta: "Reservar prueba gratuita",
    preview_data: { format: "carousel" },
    notes: "Demo interna. Diseño final en Canva/Adobe.",
    is_demo: true,
    source: "demo",
    sync_status: "manual",
    lifecycle_status: "approved"
  }
];

const demoEvents = [
  {
    id: "50000000-0000-4000-8000-000000000101",
    client_id: demoClients[0].id,
    campaign_id: demoCampaigns[0].id,
    content_item_id: demoContent[0].id,
    title: "Publicación REEL-001 Brasa Norte",
    type: "Publicación reel",
    status: "confirmed",
    start_at: "2026-06-07T18:30:00+02:00",
    end_at: "2026-06-07T19:00:00+02:00",
    location: "Instagram",
    notes: "Publicar reel demo con CTA a WhatsApp.",
    is_demo: true
  },
  {
    id: "50000000-0000-4000-8000-000000000102",
    client_id: demoClients[1].id,
    campaign_id: demoCampaigns[1].id,
    content_item_id: demoContent[1].id,
    title: "Revisión POST-001 Sonrisa Ibi",
    type: "Revisión cliente",
    status: "pending",
    start_at: "2026-06-10T10:30:00+02:00",
    end_at: "2026-06-10T11:00:00+02:00",
    location: "Stats",
    notes: "Revisar copy y visual antes de programar.",
    is_demo: true
  },
  {
    id: "50000000-0000-4000-8000-000000000103",
    client_id: demoClients[2].id,
    campaign_id: demoCampaigns[2].id,
    content_item_id: demoContent[2].id,
    title: "Entrega CAR-001 FitBox",
    type: "Entrega",
    status: "pending",
    start_at: "2026-06-11T16:00:00+02:00",
    end_at: "2026-06-11T16:30:00+02:00",
    location: "Stats",
    notes: "Preparar slides finales y CTA.",
    is_demo: true
  }
];

export async function seedStatsDemoData(db: SupabaseClient) {
  await upsert(db, "clients", demoClients, "id");
  await upsert(db, "campaigns", demoCampaigns, "id");
  await upsert(db, "monthly_metrics", demoMetrics, "client_id,month,year");
  await upsert(db, "content_items", demoContent, "id");
  await upsert(db, "calendar_events", demoEvents, "id");

  return {
    clients: demoClients.length,
    campaigns: demoCampaigns.length,
    metrics: demoMetrics.length,
    content: demoContent.length,
    calendarEvents: demoEvents.length,
    mode: "non_destructive_upsert"
  };
}

async function upsert(
  db: SupabaseClient,
  table: string,
  rows: Record<string, unknown>[],
  onConflict: string
) {
  const { error } = await db.from(table).upsert(rows, { onConflict });

  if (error) {
    throw new Error(`${table}: ${error.message}`);
  }
}
