/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in normal projects. It is committed here so
// the scaffold type-checks before the first local dev run.
